name: Deploy on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Ensure this matches the runner label in your EC2 instance
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Runner Access
        run: |
          echo "Running on self-hosted EC2 instance"
          whoami
          hostname

      - name: Run Deployment Commands
        run: |
          cd /home/ubuntu
          ls /home/ubuntu
          git clone https://github.com/shivanee99/aws-login.git
