name: awslogin

on:
  push:
    branches:
      - main

jobs:
  aws-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: us-east-1
      
      - name: Launch Ec2 instance
        run: |
          aws ec2 run-instances \
          --image-id ami-04b4f1a9cf54c11d0 \  
          --count 1 \
          --instance-type t2.micro \
          --key-name github-action \  # Replace with your key pair
          --security-groups default \  # Replace with your security group
          --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=GitHubActions-EC2}]'
    
