name: awslogin

on:
 push:
  branches:
  - main

jobs:
  aws-login:
     runs-on: ubuntu-latest
     steps:
     - name: checkout
       uses: actions/checkout@v1

     - name: configure aws creds
     - uses: aes-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}} 
         aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}} 
         aws-region: us-east-1



  
  
